-- candidate_issues(c_id int, policy varchar(45), stance varchar(45), stancedetail varchar(120));

insert into candidate_issues values('1234', 'affirmative action', 'support', 'voted for and believes in enforcing it');
insert into candidate_issues values('1234', 'equal pay', 'support', 'believes men and women should be paid the same only on merit');
insert into candidate_issues values('1234', 'disabled rights', 'support', 'encourages expanding opportunities for the disabled');
insert into candidate_issues values('1234', 'racial profiling', 'against', 'wants to end and ban racial profiling');
insert into candidate_issues values('1234', 'guncontrol', 'support', 'believes it is necessary to fight gun violence');
insert into candidate_issues values('1234', 'NSA', 'support', 'wants more transparency');
insert into candidate_issues values('1234', 'privacy', 'N/A', 'has suggested that privacy should be respected but security should not be comprimised');
insert into candidate_issues values('1234', 'drones', 'support', 'believes they are an effective counter-terrorism strategy');
insert into candidate_issues values('1234', 'waterboarding', 'against', 'likens it to torture and unnecessary');
insert into candidate_issues values('1234', 'Guantanamo', 'against', 'supported President Obamas decision on closing it down');
insert into candidate_issues values('1234', 'nuclear warfare', 'support', 'has voted in most cases for, although recently opposed an expansion of nuclear weapons');
insert into candidate_issues values('1234', 'terrorism', 'against', 'does not agree with current strategies');
insert into candidate_issues values('1234', 'military spending', 'support', 'has a long-held pro-defense spending record');
insert into candidate_issues values('1234', 'veterans affairs', 'support', 'believes VA need reform not privitization');
insert into candidate_issues values('1234', 'mandatory draft', 'N/A', 'N/A');
insert into candidate_issues values('1234', 'abortion', 'support', 'believe it is a womans right and decision');
insert into candidate_issues values('1234', 'LGBTRights', 'support', 'has supported LGBT rights and marriage');
insert into candidate_issues values('1234', 'DADT', 'support', 'no longer fully agrees with it, but voted for it and considers it a defensive action');
insert into candidate_issues values('1234', 'samesex marriage', 'support', 'has supported samesex marriage and LGBT rightss');
insert into candidate_issues values('1234', 'death penalty', 'support', 'wants to limit it and apply restrictions');
insert into candidate_issues values('1234', 'police militarization', 'against', 'believes ending it will decrease violence');
insert into candidate_issues values('1234', 'juvenile incarceration', 'against', 'believes in less harsh sentences');
insert into candidate_issues values('1234', 'marijuana legalization', 'against', 'believes in decriminalization not legalization and wants research on medicinal uses');
insert into candidate_issues values('1234', 'mexico border', 'support', 'has supported strong border security and fence and/or wall');
insert into candidate_issues values('1234', 'nonviolent_incarceration', 'against', 'believes the number of nonviolent offenders imprisoned is too high');
insert into candidate_issues values('1234', 'Israel_palestine', 'Israel', 'supports Israel');
insert into candidate_issues values('1234', 'foreign involvement', 'support', 'believes in foreign involvement and intervention');
insert into candidate_issues values('1234', 'foreign aid', 'support', 'believes in foreign aid and assistance');
insert into candidate_issues values('1234', 'foreign surveillance', 'support', 'believes it is necessary');
insert into candidate_issues values('1234', 'alternative energy', 'support', 'believes in renewable energy');
insert into candidate_issues values('1234', 'global warming', 'support', 'believes it exist, but still has fossil fuel interests');
insert into candidate_issues values('1234', 'tax reform', 'support', 'believes tax reform is needed');
insert into candidate_issues values('1234', 'social_security', 'support', 'believes it must be preserved');
insert into candidate_issues values('1234', 'freetrade', 'support', 'has supported various free trade deals and NAFTA');
insert into candidate_issues values('1234', 'deportation', 'against', 'with the exception of violent criminals');
insert into candidate_issues values('1234', 'amnesty', 'support', 'has proposed a path to full and equal citizenship');
insert into candidate_issues values('1234', 'illegal_immigration', 'support', 'has supported a path to citizenship and that they should be able to participate in Obamacare');
insert into candidate_issues values('1234', 'borderwall', 'support', 'has agreed to building a wall on the the US-Mexican Border');
insert into candidate_issues values('1234', 'medicare', 'support', 'believes it must be preserved');
insert into candidate_issues values('1234', 'universal_healthcare', 'support', 'believes obamacare is a start');

