-- candidate_issues(c_id int, policy varchar(45), stance varchar(45), stancedetail varchar(120));

insert into candidate_issues values('8008', 'affirmative action', 'against', 'has stated he does not support it and wants to end it');
insert into candidate_issues values('8008', 'equal pay', 'support', 'does not think it is an issue and believes it has been the unwritten law for decades');
insert into candidate_issues values('8008', 'disabled rights', 'support', 'believes in empowering them and supports them');
insert into candidate_issues values('8008', 'racial profiling', 'support', 'has advocated policies in support of profiling');
insert into candidate_issues values('8008', 'guncontrol', 'against', 'believes it is unarguably 2nd amendment right');
insert into candidate_issues values('8008', 'NSA', 'against', 'is against bulk data collection');
insert into candidate_issues values('8008', 'privacy', 'N/A', 'N/A');
insert into candidate_issues values('8008', 'drones', 'support', 'however only supports foreign use, against domestic use');
insert into candidate_issues values('8008', 'waterboarding', 'support', 'does not consider it torture and advocates its use in certain situations');
insert into candidate_issues values('8008', 'Guantanamo', 'support', 'wants to keep Guantanamo open');
insert into candidate_issues values('8008', 'nuclear warfare', 'support', 'has expressed support, has also stated willing to use when necessary');
insert into candidate_issues values('8008', 'terrorism', 'against', 'wants tougher regulations and tighten security');
insert into candidate_issues values('8008', 'military spending', 'support', 'wants to increase military spending budget');
insert into candidate_issues values('8008', 'veterans affairs', 'support', 'wants privatization of VA');
insert into candidate_issues values('8008', 'mandatory draft', 'N/A', 'N/A');
insert into candidate_issues values('8008', 'abortion', 'against', 'pro-life without exceptions');
insert into candidate_issues values('8008', 'LGBTRights', 'against', 'has opposed a variety of LGBT rights');
insert into candidate_issues values('8008', 'DADT', 'support', 'has suggesting bringing it back');
insert into candidate_issues values('8008', 'samesex marriage', 'against', 'has expressed his opposition explicitly');
insert into candidate_issues values('8008', 'death penalty', 'support', 'believes it should be used for the most heinous');
insert into candidate_issues values('8008', 'police militarization', 'neutral', 'no clear stance, conflicting statements');
insert into candidate_issues values('8008', 'juvenile incarceration', 'N/A', 'has stated justice system needs reform but not specifically');
insert into candidate_issues values('8008', 'marijuana legalization', 'against', 'believes it is a gateway drug');
insert into candidate_issues values('8008', 'mexico border', 'suppors', 'wants to increase border security');
insert into candidate_issues values('8008', 'nonviolent_incarceration', 'neutral', 'has stated the need for reform but not specifically');
insert into candidate_issues values('8008', 'Israel_palestine', 'Israel', 'has expressed his support and that he stands with Israel');
insert into candidate_issues values('8008', 'foreign involvement', 'neutral', 'suggested limiting foreign intervention');
insert into candidate_issues values('8008', 'foreign aid', 'neutral', 'in general has not expressed support, but has supported Israel and Ukraine');
insert into candidate_issues values('8008', 'foreign surveillance', 'against', 'with the exception of specific countries that he would be fine with surveillancing');
insert into candidate_issues values('8008', 'alternative energy', 'support', 'has supported all types of energy including a variety of alternative energies');
insert into candidate_issues values('8008', 'global warming', 'against', 'does not believe in the existence of global climate change of any kind');
insert into candidate_issues values('8008', 'tax reform', 'support', 'believes there needs to be extensive tax reform');
insert into candidate_issues values('8008', 'social_security', 'support', 'wants to "preserve and strengthen Social Security"');
insert into candidate_issues values('8008', 'freetrade', 'support', 'believes it is beneficial to the US');
insert into candidate_issues values('8008', 'deportation', 'support', 'wants to deport 11 Million illegal immigrants');
insert into candidate_issues values('8008', 'amnesty', 'against', 'has expressed opposition to any such plan');
insert into candidate_issues values('8008', 'illegal_immigration', 'against', 'wants to deport illegal immigrants, all 11 Million');
insert into candidate_issues values('8008', 'borderwall', 'support', 'has stated supports building a wall on US-Mexico Border');
insert into candidate_issues values('8008', 'medicare', 'support', ' however, wants to graudually increase eligibility age');
insert into candidate_issues values('8008', 'universal_healthcare', 'N/A', 'N/A');

