-- candidate_issues(c_id int, policy varchar(45), stance varchar(45), stancedetail varchar(120));

insert into candidate_issues values('7789', 'affirmative action', 'support', 'Affirmative action OK via recruitment not via quotas ');
insert into candidate_issues values('7789', 'equal pay', 'neutral', 'believes it is based on experience');
insert into candidate_issues values('7789', 'disabled rights', 'support', 'N/A');
insert into candidate_issues values('7789', 'racial profiling', 'against', 'wants an end to it');
insert into candidate_issues values('7789', 'guncontrol', 'against', 'is against current implementation, however has alternatives');
insert into candidate_issues values('7789', 'NSA', 'support', 'wants regulation and restrictions');
insert into candidate_issues values('7789', 'privacy', 'neutral', 'N/A');
insert into candidate_issues values('7789', 'drones', 'support', 'wants program relocated from CIA to Pentagon');
insert into candidate_issues values('7789', 'waterboarding', 'N/A', 'N/A');
insert into candidate_issues values('7789', 'Guantanamo', 'support', 'does not believe in closing of Guantanamo');
insert into candidate_issues values('7789', 'nuclear warfare', 'support', 'proven by voting record');
insert into candidate_issues values('7789', 'terrorism', 'against', 'believes it is of immediate concern');
insert into candidate_issues values('7789', 'military spending', 'support', 'wants to increase defense spending, but cut wasteful spending');
insert into candidate_issues values('7789', 'veterans affairs', 'support', 'supports better management and less centralization');
insert into candidate_issues values('7789', 'mandatory draft', 'N/A', 'N/A');
insert into candidate_issues values('7789', 'abortion', 'against', 'however, believes that there are exceptions');
insert into candidate_issues values('7789', 'LGBTRights', 'against', 'personally against it but agrees to uphold supreme court decision');
insert into candidate_issues values('7789', 'DADT', 'support', 'voted in favor in 1993');
insert into candidate_issues values('7789', 'samesex marriage', 'against', 'personally against it but agrees to uphold supreme court decision');
insert into candidate_issues values('7789', 'death penalty', 'support', 'said “I support the death penalty and will continue to do that”');
insert into candidate_issues values('7789', 'police militarization', 'neutral', 'believes it is under local control, is ok with required police body cams');
insert into candidate_issues values('7789', 'juvenile incarceration', 'against', 'believes that the juvenile justice program needs reform');
insert into candidate_issues values('7789', 'marijuana legalization', 'against', 'is against recreational use, will support medical marijuana if concrete evidence');
insert into candidate_issues values('7789', 'mexico border', 'support', 'beleives in enforcing the border with a wall');
insert into candidate_issues values('7789', 'nonviolent_incarceration', 'against', 'believes nonviolent crimes should have shorter sentences and rehabilitation should be provided');
insert into candidate_issues values('7789', 'Israel_palestine', 'israel', 'supports Israel as they are an ally');
insert into candidate_issues values('7789', 'foreign involvement', 'support', 'believes it is necessary and in the best interest of US');
insert into candidate_issues values('7789', 'foreign aid', 'support', 'believes it is necessary');
insert into candidate_issues values('7789', 'foreign surveillance', 'support', 'N/A');
insert into candidate_issues values('7789', 'alternative energy', 'support', 'believes renewable energy is the future');
insert into candidate_issues values('7789', 'global warming', 'support', 'believes in climate change just not to a limited extent');
insert into candidate_issues values('7789', 'tax reform', 'support', 'believes in cutting taxes');
insert into candidate_issues values('7789', 'social_security', 'support', 'believes there need to be reform');
insert into candidate_issues values('7789', 'freetrade', 'support', 'wants free and open trade');
insert into candidate_issues values('7789', 'deportation', 'against', 'believes that it is absurd to deport 11 Million people');
insert into candidate_issues values('7789', 'amnesty', 'support', 'refers to it as a path to legalization rather than amnesty due to selectivity');
insert into candidate_issues values('7789', 'illegal_immigration', 'against', 'however believes in allowing a path to legalization');
insert into candidate_issues values('7789', 'borderwall', 'support', 'believes in border security and a border wall is a form of security');
insert into candidate_issues values('7789', 'medicare', 'support', 'believes in expansion of Medicaid and Medicare');
insert into candidate_issues values('7789', 'universal_healthcare', 'N/A', 'N/A');

