-- candidate_issues(c_id int, policy varchar(45), stance varchar(45), stancedetail varchar(120));

insert into candidate_issues values('6102', 'affirmative action', 'support', 'scored 97% by the NAACP on affirmative action');
insert into candidate_issues values('6102', 'equal pay', 'support', 'has voted for equal pay and strongly supports');
insert into candidate_issues values('6102', 'disabled rights', 'support', 'believes it is necessary');
insert into candidate_issues values('6102', 'racial profiling', 'against', 'N/A');
insert into candidate_issues values('6102', 'guncontrol', 'support', 'necessary to combat gun violence');
insert into candidate_issues values('6102', 'NSA', 'against', 'does not believe in the current policies nor implementation');
insert into candidate_issues values('6102', 'privacy', 'support', 'does not believe in infringing privacy');
insert into candidate_issues values('6102', 'drones', 'support', 'limited use and little to no collateral damage');
insert into candidate_issues values('6102', 'waterboarding', 'against', 'considers it unacceptable and torture');
insert into candidate_issues values('6102', 'Guantanamo', 'against', 'praised President Obama on shutting down Guantanamo');
insert into candidate_issues values('6102', 'nuclear warfare', 'against', 'believes in decreasing nuclear weapons spending');
insert into candidate_issues values('6102', 'terrorism', 'against', 'still believes there needs to be reform in dealing with it');
insert into candidate_issues values('6102', 'military spending', 'against', 'believes it needs to be decreased');
insert into candidate_issues values('6102', 'veterans affairs', 'support', 'however against the privatization of VA');
insert into candidate_issues values('6102', 'mandatory draft', 'N/A', 'N/A');
insert into candidate_issues values('6102', 'abortion', 'support', 'believes it is a womans right and decision');
insert into candidate_issues values('6102', 'LGBTRights', 'support', 'has a long record supporting LGBT Rights');
insert into candidate_issues values('6102', 'DADT', 'against', 'voted against it in 1993');
insert into candidate_issues values('6102', 'samesex marriage', 'support', 'has a long record in support of LGBT Rights including marriage');
insert into candidate_issues values('6102', 'death penalty', 'against', 'supports repealment');
insert into candidate_issues values('6102', 'police militarization', 'against', 'supports demilitarization');
insert into candidate_issues values('6102', 'juvenile incarceration', 'against', 'believes that it is damaging to record');
insert into candidate_issues values('6102', 'marijuana legalization', 'support', 'supports legalization of both medical and recreational marijuana');
insert into candidate_issues values('6102', 'mexico border', 'against', 'does not believe the border needs any further securing');
insert into candidate_issues values('6102', 'nonviolent_incarceration', 'against', 'believes it damages record and is wrong');
insert into candidate_issues values('6102', 'Israel_palestine', 'neutral', 'believes there should be mutual agreement, both have a right to exist');
insert into candidate_issues values('6102', 'foreign involvement', 'against', 'does not believe in extensive foreign involvement or intervention');
insert into candidate_issues values('6102', 'foreign aid', 'neutral', 'foreign aid must be reduced, but not terminated');
insert into candidate_issues values('6102', 'foreign surveillance', 'against', 'believes it damages foreign relations');
insert into candidate_issues values('6102', 'alternative energy', 'support', 'has advocated and voted for renewable energy');
insert into candidate_issues values('6102', 'global warming', 'support', 'believes it exists and that it is a problem');
insert into candidate_issues values('6102', 'tax reform', 'support', 'believes in tax reform and income wealth distribution');
insert into candidate_issues values('6102', 'social_security', 'support', 'believes it is of great importance');
insert into candidate_issues values('6102', 'freetrade', 'against', 'voted against free trade deals, especially destructive ones');
insert into candidate_issues values('6102', 'deportation', 'against', 'opposed to mass deportation of children and nonviolent illegal immigrants');
insert into candidate_issues values('6102', 'amnesty', 'support', 'believes in at least a path to legalization');
insert into candidate_issues values('6102', 'illegal_immigration', 'support', 'believes as a nation of immigrant, we should help, and there needs to be reform');
insert into candidate_issues values('6102', 'borderwall', 'against', 'voted against a fence, a wall is a definite no');
insert into candidate_issues values('6102', 'medicare', 'support', 'believes in a medicare for all');
insert into candidate_issues values('6102', 'universal_healthcare', 'support', 'believes in a unviersal healthcare for all plan');

