-- candidate_issues(c_id int, policy varchar(45), stance varchar(45), stancedetail varchar(120));

insert into candidate_issues values('7734', 'affirmative action', 'support', 'has expressed he is ok with it');
insert into candidate_issues values('7734', 'equal pay', 'support', 'contradictory statements made');
insert into candidate_issues values('7734', 'disabled rights', 'N/A', 'N/A');
insert into candidate_issues values('7734', 'racial profiling', 'support', 'has supported use of selective racial profiling');
insert into candidate_issues values('7734', 'guncontrol', 'against', 'believes it is against 2nd amendment and also supports conceal-and-carry');
insert into candidate_issues values('7734', 'NSA', 'neutral', 'no opinion strongly for or against NSA');
insert into candidate_issues values('7734', 'privacy', 'N/A', 'N/A');
insert into candidate_issues values('7734', 'drones', 'support', 'no specific policy, but in support of airstrikes');
insert into candidate_issues values('7734', 'waterboarding', 'support', 'has supported and advocated it');
insert into candidate_issues values('7734', 'Guantanamo', 'support', 'opposes closing and vows to keep it open');
insert into candidate_issues values('7734', 'nuclear warfare', 'support', 'N/A');
insert into candidate_issues values('7734', 'terrorism', 'against', 'opposes current strategies');
insert into candidate_issues values('7734', 'military spending', 'support', 'supports funding and expansion of military budget but wants to eliminate waste spending');
insert into candidate_issues values('7734', 'veterans affairs', 'neutral', 'beleives he can make it great again');
insert into candidate_issues values('7734', 'mandatory draft', 'neutral', 'has suggested it in certain situations');
insert into candidate_issues values('7734', 'abortion', 'against', 'pro-life with exceptions');
insert into candidate_issues values('7734', 'LGBTRights', 'support', 'wants an amendment to civil rights that will ban discrimination due to sexual orientation');
insert into candidate_issues values('7734', 'DADT', 'neutral', 'supported it in the past but believes it has clearly failed');
insert into candidate_issues values('7734', 'samesex marriage', 'against', 'believes himself to be a traditional marriage guy');
insert into candidate_issues values('7734', 'death penalty', 'support','“I have always been a big believer and continue to be of the death penalty for horrendous crime”');
insert into candidate_issues values('7734', 'police militarization', 'support', 'believes they are already militarized, and he will continue to do so');
insert into candidate_issues values('7734', 'juvenile incarceration', 'neutral', 'believes that they should not be jailed for nonviolent crimes and shorter sentences');
insert into candidate_issues values('7734', 'marijuana legalization', 'against', 'against recreational use for the time being, supports medicinal marijuana');
insert into candidate_issues values('7734', 'mexico border', 'support', 'wants to increase border security');
insert into candidate_issues values('7734', 'nonviolent_incarceration', 'against', 'believes people, especially juveniles should not be jailed for nonviolent offences, especially drugs');
insert into candidate_issues values('7734', 'Israel_palestine', 'neutral', 'has chosen to remain completely neutral on the issue');
insert into candidate_issues values('7734', 'foreign involvement', 'support', 'believes in intervention when America or Americans are directly affected');
insert into candidate_issues values('7734', 'foreign aid', 'support', 'when supporting allies and in cases of national interest');
insert into candidate_issues values('7734', 'foreign surveillance', 'support', 'suggests it is for the sake of national security');
insert into candidate_issues values('7734', 'alternative energy', 'neutral', 'believes technologies remain unproven');
insert into candidate_issues values('7734', 'global warming', 'against', 'does not believe in the existence of global climate change');
insert into candidate_issues values('7734', 'tax reform', 'support', 'beleives there needs to be tax reform');
insert into candidate_issues values('7734', 'social_security', 'support', 'believes it needs saving');
insert into candidate_issues values('7734', 'freetrade', 'neutral', 'has conflicting positions, has supported in the past, now suggests to scrap');
insert into candidate_issues values('7734', 'deportation', 'support', 'wants to deport 11 Million illegal immigrants');
insert into candidate_issues values('7734', 'amnesty', 'against', 'has suggested a plan for some immigrants to stay in US');
insert into candidate_issues values('7734', 'illegal_immigration', 'against', 'has strong policies deportation and illegal immigration');
insert into candidate_issues values('7734', 'borderwall', 'support', 'believes strongly about constructing a wall');
insert into candidate_issues values('7734', 'medicare', 'support', 'thinks it works, but wants to negotiate prices');
insert into candidate_issues values('7734', 'universal_healthcare', 'support', 'wants government funded healthcare for all, however opposes Obamacare');

